import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';

interface ThemeColors {
  background: {
    primary: string;
    secondary: string;
    tertiary: string;
    elevated: string;
  };
  text: {
    primary: string;
    secondary: string;
    tertiary: string;
    inverse: string;
  };
  border: {
    default: string;
    hover: string;
    focus: string;
    subtle: string;
  };
  accent: {
    primary: string;
    success: string;
    warning: string;
    danger: string;
    info: string;
  };
}

interface ThemeConfig {
  dark: ThemeColors;
  light: ThemeColors;
  gradients: {
    primary: string;
    success: string;
    danger: string;
    warning: string;
    info: string;
  };
}

interface Config {
  frontend?: {
    theme?: ThemeConfig;
  };
}

const DEFAULT_CONFIG_PATH = path.resolve(__dirname, '../../../config.yml');

function loadThemeConfig(): ThemeConfig {
  try {
    const configPath = process.env.SOLAI_CONFIG_PATH || DEFAULT_CONFIG_PATH;
    if (!fs.existsSync(configPath)) {
      console.warn(`Config file not found at ${configPath}, using default theme`);
      return getDefaultTheme();
    }
    
    const fileContents = fs.readFileSync(configPath, 'utf8');
    const config = yaml.load(fileContents) as Config;
    
    if (!config.frontend?.theme) {
      console.warn('No theme configuration found in config.yml, using default theme');
      return getDefaultTheme();
    }
    
    return config.frontend.theme;
  } catch (error) {
    console.error('Error loading theme config:', error);
    return getDefaultTheme();
  }
}

function getDefaultTheme(): ThemeConfig {
  return {
    dark: {
      background: {
        primary: '#0f172a',
        secondary: '#1e293b',
        tertiary: '#334155',
        elevated: '#475569',
      },
      text: {
        primary: '#f1f5f9',
        secondary: '#cbd5e1',
        tertiary: '#94a3b8',
        inverse: '#0f172a',
      },
      border: {
        default: '#334155',
        hover: '#475569',
        focus: '#6366f1',
        subtle: '#475569',
      },
      accent: {
        primary: '#6366f1',
        success: '#10b981',
        warning: '#f59e0b',
        danger: '#ef4444',
        info: '#3b82f6',
      },
    },
    light: {
      background: {
        primary: '#ffffff',
        secondary: '#f8fafc',
        tertiary: '#f1f5f9',
        elevated: '#e2e8f0',
      },
      text: {
        primary: '#0f172a',
        secondary: '#475569',
        tertiary: '#64748b',
        inverse: '#f1f5f9',
      },
      border: {
        default: '#e2e8f0',
        hover: '#cbd5e1',
        focus: '#6366f1',
        subtle: '#f1f5f9',
      },
      accent: {
        primary: '#4f46e5',
        success: '#059669',
        warning: '#d97706',
        danger: '#dc2626',
        info: '#2563eb',
      },
    },
    gradients: {
      primary: 'from-emerald-400 to-purple-400',
      success: 'from-emerald-500 to-green-600',
      danger: 'from-red-500 to-pink-600',
      warning: 'from-amber-500 to-orange-600',
      info: 'from-blue-500 to-indigo-600',
    },
  };
}

export function generateThemeCSS(): string {
  const theme = loadThemeConfig();
  
  return `
/* Auto-generated theme variables from config.yml */
/* DO NOT EDIT THIS FILE DIRECTLY - Edit config.yml instead */

:root {
  /* Gradient Classes */
  --gradient-primary: ${theme.gradients.primary};
  --gradient-success: ${theme.gradients.success};
  --gradient-danger: ${theme.gradients.danger};
  --gradient-warning: ${theme.gradients.warning};
  --gradient-info: ${theme.gradients.info};
}

.dark {
  /* Dark Theme */
  --bg-primary: ${theme.dark.background.primary};
  --bg-secondary: ${theme.dark.background.secondary};
  --bg-tertiary: ${theme.dark.background.tertiary};
  --bg-elevated: ${theme.dark.background.elevated};

  --text-primary: ${theme.dark.text.primary};
  --text-secondary: ${theme.dark.text.secondary};
  --text-tertiary: ${theme.dark.text.tertiary};
  --text-inverse: ${theme.dark.text.inverse};

  --border-default: ${theme.dark.border.default};
  --border-hover: ${theme.dark.border.hover};
  --border-focus: ${theme.dark.border.focus};
  --border-subtle: ${theme.dark.border.subtle};

  --accent-primary: ${theme.dark.accent.primary};
  --accent-success: ${theme.dark.accent.success};
  --accent-warning: ${theme.dark.accent.warning};
  --accent-danger: ${theme.dark.accent.danger};
  --accent-info: ${theme.dark.accent.info};
}

.light {
  /* Light Theme */
  --bg-primary: ${theme.light.background.primary};
  --bg-secondary: ${theme.light.background.secondary};
  --bg-tertiary: ${theme.light.background.tertiary};
  --bg-elevated: ${theme.light.background.elevated};

  --text-primary: ${theme.light.text.primary};
  --text-secondary: ${theme.light.text.secondary};
  --text-tertiary: ${theme.light.text.tertiary};
  --text-inverse: ${theme.light.text.inverse};

  --border-default: ${theme.light.border.default};
  --border-hover: ${theme.light.border.hover};
  --border-focus: ${theme.light.border.focus};
  --border-subtle: ${theme.light.border.subtle};

  --accent-primary: ${theme.light.accent.primary};
  --accent-success: ${theme.light.accent.success};
  --accent-warning: ${theme.light.accent.warning};
  --accent-danger: ${theme.light.accent.danger};
  --accent-info: ${theme.light.accent.info};
}
`;
}

export { loadThemeConfig };
